CREATE TABLE TBLEMPLOYEE
(
	FLDNAME			VARCHAR(20)
	,FLDAGE			INT
	,FLDDOB			DATE
	,FLDMOBILE		BIGINT
	,FLDLOCATION	VARCHAR(20)
	,FLDDEPARTMENT	VARCHAR(30)
)

INSERT INTO TBLEMPLOYEE
(
	FLDNAME		
	,FLDAGE		
	,FLDDOB		
	,FLDMOBILE	
	,FLDLOCATION
)
VALUES
	('GANESH', 23, '2001-04-25', 6374062485, 'SRIVI', 'TRAINEE PROGRAMMER')
	,('LINGAM', 30, '1996-03-15', 9749246638, 'BENGALURU', 'SENIOR SOFTWARE DEVELOPER')
	,('BAABHU', 34, '1993-12-12', 7896543210, 'CHENNAI', 'HR');

DROP TABLE TBLEMPLOYEE

CREATE TABLE TBLDEPARTMENT
(
	FLDDEPARTMENTID		INT			IDENTITY(1,1)
	,FLDDEPARTMENT		VARCHAR(20)
)

ALTER TABLE TBLDEPARTMENT 
ALTER COLUMN FLDDEPARTMENT VARCHAR(30)

INSERT INTO TBLDEPARTMENT
(
	FLDDEPARTMENT
)
VALUES
	('TEAM LEADER')
	,('SENIOR SOFTWARE DEVELOPER')
	,('JUNIOR SOFTWARE DEVELOPER')
	,('TRAINEE PROGRAMMER')
	,('HR')
	,('FROUNTEND DEVELOPER')
	,('BACKEND DEVELOPER')

ALTER TABLE TBLDEPARTMENT
ADD FLDDEPARTMENTID INT IDENTITY(1,1)

SELECT * FROM TBLDEPARTMENT

DROP TABLE TBLDEPARTMENT


CREATE TABLE TBLSALARY
(
	FLDDEPARTMENTID		INT		IDENTITY(1,1)
	,FLDSALARY			INT
)

INSERT INTO TBLSALARY(FLDSALARY)
VALUES
	(80000)
	,(70000)
	,(60000)
	,(18000)
	,(50000)
	,(30000)
	,(40000)

SELECT * FROM TBLSALARY

SELECT EM.*
FROM TBLEMPLOYEE EM

SELECT * FROM TBLSALARY

SELECT * FROM TBLDEPARTMENT